/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorConsultaEstudiante;
import javax.swing.table.DefaultTableModel;
import controlador.OperacionesListaEstudianteCRUD;
import java.util.ArrayList;
import modelo.EstudianteObj;

/**
 *
 * @author juare
 */
public class EstudianteConsulta extends javax.swing.JFrame {

    /**
     * Creates new form EstudianteConsulta
     */
   
    OperacionesListaEstudianteCRUD objListaEst;
    ControladorConsultaEstudiante objControladorEstudiante;
    
    //EstudianteObj objEstudiante;
    public EstudianteConsulta( ) {
        initComponents();
        objControladorEstudiante = new ControladorConsultaEstudiante(this);
         
       
    }
    public EstudianteConsulta(OperacionesListaEstudianteCRUD objListaEst) {
        initComponents();
        objControladorEstudiante = new ControladorConsultaEstudiante(this);  
        this.objListaEst=objListaEst;
        llenado();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1Alta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricula", "Nombre", "Ape Paterno", "Ape Materno"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("AGREGAR ");

        jButton1Alta.setText("Alta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton1Alta)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1Alta))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public void llenado(){
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setRowCount(0);
        ArrayList<EstudianteObj> objListaEstudianteLocal =  objListaEst.read();
        
        for(int i=0;i<objListaEstudianteLocal.size(); i++){
            modelo.addRow(new Object[]{objListaEstudianteLocal.get(i).getMatricula(), objListaEstudianteLocal.get(i).getNombre(),
                objListaEstudianteLocal.get(i).getApPaterno(), objListaEstudianteLocal.get(i).getApMaterno(),
                objListaEstudianteLocal.get(i).getEdad()});
        }
       /* for(int i=0;i<ObjLista.objListaEstudiante.size(); i++){
            modelo.addRow(new Object[]{
            ObjLista.objListaEstudiante.get(i).getMatricula(),
            ObjLista.objListaEstudiante.get(i).getNombre(),
            ObjLista.objListaEstudiante.get(i).getApPaterno(),
            ObjLista.objListaEstudiante.get(i).getApMaterno()
        });
        }*/
        
    }
    /*public void llenado(){
        DefaultTableModel modelo = (DefaultTableModel)this.tablaAlumnos.getModel();
        modelo.addRow(new Object[]{
            objLista.objListaAlumno.get(0).getMatricula(),objLista.objListaAlumno.get(0).getNombre()});
*/
    /* public void actualizarTabla(){
        DefaultTableModel objModeloTabla = (DefaultTableModel) this.jTable1.getModel();
       
        ArrayList<EstudianteObj> objListaEstudiante =ObjListaEstudiante.getObjListaEstudiante();
        System.out.println("Cantidad de estudiantes: " + objListaEstudiante.size());
        this.ObjListaEstudiante.read();
        
        for (int i = 0; i < objListaEstudiante.size(); i++) {
            
             EstudianteObj estudiante = objListaEstudiante.get(i); 
             objModeloTabla.addRow(new Object[]{
             estudiante.getMatricula(),
             estudiante.getNombre(), 
             estudiante.getApPaterno(),
             estudiante.getApMaterno()});
    }
        this.jButton1.setModel((ButtonModel) objListaEstudiante);
}  */
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteConsulta().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1Alta;
    public javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   

   
}
